-- 0007_add_answer_images_bucket_and_policies.sql
-- 新增 answer_images 表（结构与 question_images 一致），并为存储 bucket 写入策略

-- 1) 表结构
CREATE TABLE IF NOT EXISTS public.answer_images (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at   timestamptz DEFAULT now() NOT NULL,
  question_id  bigint NOT NULL,
  storage_path text NOT NULL,
  position     smallint NOT NULL,
  CONSTRAINT answer_images_storage_path_key UNIQUE (storage_path),
  CONSTRAINT answer_images_question_position_key UNIQUE (question_id, position),
  CONSTRAINT answer_images_question_id_fkey FOREIGN KEY (question_id)
    REFERENCES public.questions (id) ON DELETE CASCADE
);

-- 2) RLS 与策略（与 question_images 对齐）
ALTER TABLE public.answer_images ENABLE ROW LEVEL SECURITY;

CREATE POLICY "answer_images.select" ON public.answer_images
  FOR SELECT
  USING (true);

CREATE POLICY "answer_images.insert" ON public.answer_images
  FOR INSERT
  WITH CHECK (public.in_roles(VARIADIC ARRAY['admin'::public.user_role, 'super_admin'::public.user_role]));

CREATE POLICY "answer_images.update" ON public.answer_images
  FOR UPDATE
  USING (public.in_roles(VARIADIC ARRAY['admin'::public.user_role, 'super_admin'::public.user_role]))
  WITH CHECK (public.in_roles(VARIADIC ARRAY['admin'::public.user_role, 'super_admin'::public.user_role]));

CREATE POLICY "answer_images.delete" ON public.answer_images
  FOR DELETE
  USING (public.in_roles(VARIADIC ARRAY['admin'::public.user_role, 'super_admin'::public.user_role]));

-- 3) Grants（保持与现有表一致）
GRANT ALL ON TABLE public.answer_images TO anon, authenticated, service_role;
GRANT ALL ON SEQUENCE public.answer_images_id_seq TO anon, authenticated, service_role;

-- 4) Storage bucket 与对象级策略（与 question_images 一致）
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'answer_images',
  'answer_images',
  FALSE,
  52428800,
  '{"image/*"}'::text[]
)
ON CONFLICT (id) DO UPDATE
SET
  public             = EXCLUDED.public,
  file_size_limit    = EXCLUDED.file_size_limit,
  allowed_mime_types = EXCLUDED.allowed_mime_types;

-- 允许已登录用户读取 answer_images bucket 下的对象
CREATE POLICY "answer_images_select_authenticated"
ON storage.objects
FOR SELECT
TO authenticated
USING (bucket_id = 'answer_images');

-- 只允许 admin / super_admin 上传
CREATE POLICY "answer_images_insert_admins"
ON storage.objects
FOR INSERT
TO authenticated
WITH CHECK (
  bucket_id = 'answer_images'
  AND public.in_roles(VARIADIC ARRAY['admin'::public.user_role, 'super_admin'::public.user_role])
);

-- 只允许 admin / super_admin 更新
CREATE POLICY "answer_images_update_admins"
ON storage.objects
FOR UPDATE
TO authenticated
USING (
  bucket_id = 'answer_images'
  AND public.in_roles(VARIADIC ARRAY['admin'::public.user_role, 'super_admin'::public.user_role])
)
WITH CHECK (
  bucket_id = 'answer_images'
  AND public.in_roles(VARIADIC ARRAY['admin'::public.user_role, 'super_admin'::public.user_role])
);

-- 只允许 admin / super_admin 删除
CREATE POLICY "answer_images_delete_admins"
ON storage.objects
FOR DELETE
TO authenticated
USING (
  bucket_id = 'answer_images'
  AND public.in_roles(VARIADIC ARRAY['admin'::public.user_role, 'super_admin'::public.user_role])
);
