-- 0002_init_schema.sql
-- 所有表、序列、索引、主键 / 唯一键、外键

-- chapters
CREATE TABLE IF NOT EXISTS "public"."chapters" (
    "id" bigint NOT NULL,
    "subject_id" bigint NOT NULL,
    "parent_chapter_id" bigint,
    "name" "text" NOT NULL,
    "position" smallint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    CONSTRAINT "subject_chapters_parent" CHECK (
        ( "parent_chapter_id" IS NULL )
        OR ( "parent_chapter_id" <> "id" )
    )
);

ALTER TABLE "public"."chapters"
    ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME "public"."chapters_id_seq"
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1
    );

-- exam_boards
CREATE TABLE IF NOT EXISTS "public"."exam_boards" (
    "id" bigint NOT NULL,
    "name" "text" NOT NULL,
    "question_bank" "public"."question_bank" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);

ALTER TABLE "public"."exam_boards"
    ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME "public"."exam_boards_id_seq"
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1
    );

-- profiles
CREATE TABLE IF NOT EXISTS "public"."profiles" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "role" "public"."user_role" DEFAULT 'user'::"public"."user_role" NOT NULL,
    "email" "text" NOT NULL
);

-- question_images
CREATE TABLE IF NOT EXISTS "public"."question_images" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "question_id" bigint NOT NULL,
    "storage_path" "text" NOT NULL,
    "position" smallint NOT NULL
);

ALTER TABLE "public"."question_images"
    ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME "public"."question_images_id_seq"
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1
    );

-- questions
CREATE TABLE IF NOT EXISTS "public"."questions" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "difficulty" smallint DEFAULT '2'::smallint NOT NULL,
    "calculator" boolean DEFAULT true NOT NULL,
    "marks" smallint NOT NULL,
    CONSTRAINT "questions_difficulty_check" CHECK (
        ( "difficulty" >= 1 ) AND ( "difficulty" <= 4 )
    ),
    CONSTRAINT "questions_marks_check" CHECK (
        "marks" > 0
    )
);

ALTER TABLE "public"."questions"
    ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME "public"."questions_id_seq"
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1
    );

-- 独立序列：subject_chapters_id_seq
CREATE SEQUENCE IF NOT EXISTS "public"."subject_chapters_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE "public"."subject_chapters_id_seq" OWNED BY "public"."chapters"."id";

-- subjects
CREATE TABLE IF NOT EXISTS "public"."subjects" (
    "id" bigint NOT NULL,
    "exam_board_id" bigint NOT NULL,
    "name" "text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);

ALTER TABLE "public"."subjects"
    ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME "public"."subjects_id_seq"
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1
    );

-- tags
CREATE TABLE IF NOT EXISTS "public"."tags" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "name" "text" NOT NULL,
    "parent_id" bigint
);

ALTER TABLE "public"."tags"
    ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME "public"."tag_id_seq"
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1
    );

-- user_questions
CREATE TABLE IF NOT EXISTS "public"."user_questions" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "user_id" "uuid" NOT NULL,
    "question_id" bigint,
    "is_bookmarked" boolean DEFAULT false NOT NULL,
    "completed_at" timestamp with time zone,
    "last_viewed_at" timestamp with time zone,
    "answer_viewed_at" timestamp with time zone,
    "answer_view_count" integer DEFAULT 0
);

ALTER TABLE "public"."user_questions"
    ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME "public"."user_questions_id_seq"
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1
    );

-- question_chapters (多对多关联表)
CREATE TABLE IF NOT EXISTS "public"."question_chapters" (
    "question_id" bigint NOT NULL,
    "chapter_id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);

-- ========= 主键 & 唯一约束 =========

ALTER TABLE ONLY "public"."exam_boards"
    ADD CONSTRAINT "exam_boards_name_key" UNIQUE ("name");

ALTER TABLE ONLY "public"."exam_boards"
    ADD CONSTRAINT "exam_boards_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."profiles"
    ADD CONSTRAINT "profiles_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."question_images"
    ADD CONSTRAINT "question_images_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."question_images"
    ADD CONSTRAINT "question_images_storage_path_key" UNIQUE ("storage_path");

ALTER TABLE ONLY "public"."questions"
    ADD CONSTRAINT "questions_id_key" UNIQUE ("id");

ALTER TABLE ONLY "public"."questions"
    ADD CONSTRAINT "questions_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."chapters"
    ADD CONSTRAINT "subject_chapters_id_subject_id_key" UNIQUE ("id", "subject_id");

ALTER TABLE ONLY "public"."chapters"
    ADD CONSTRAINT "subject_chapters_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."chapters"
    ADD CONSTRAINT "subject_chapters_subject_id_name_key" UNIQUE ("subject_id", "name");

ALTER TABLE ONLY "public"."subjects"
    ADD CONSTRAINT "subjects_exam_board_id_name_key" UNIQUE ("exam_board_id", "name");

ALTER TABLE ONLY "public"."subjects"
    ADD CONSTRAINT "subjects_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."tags"
    ADD CONSTRAINT "tag_id_key" UNIQUE ("id");

ALTER TABLE ONLY "public"."tags"
    ADD CONSTRAINT "tag_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."user_questions"
    ADD CONSTRAINT "user_questions_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."user_questions"
    ADD CONSTRAINT "user_questions_user_id_question_id_key" UNIQUE ("user_id", "question_id");

ALTER TABLE ONLY "public"."question_chapters"
    ADD CONSTRAINT "question_chapters_pkey" PRIMARY KEY ("question_id", "chapter_id");

-- ========= 索引 =========

CREATE UNIQUE INDEX "question_images_question_position_key"
    ON "public"."question_images" USING "btree" ("question_id", "position");

CREATE INDEX "question_chapters_question_id_idx"
    ON "public"."question_chapters" USING "btree" ("question_id");

CREATE INDEX "question_chapters_chapter_id_idx"
    ON "public"."question_chapters" USING "btree" ("chapter_id");

-- ========= 外键 =========

ALTER TABLE ONLY "public"."chapters"
    ADD CONSTRAINT "chapters_parent_chapter_id_fkey"
    FOREIGN KEY ("parent_chapter_id")
    REFERENCES "public"."chapters"("id")
    ON DELETE CASCADE;

ALTER TABLE ONLY "public"."chapters"
    ADD CONSTRAINT "chapters_subject_id_fkey"
    FOREIGN KEY ("subject_id")
    REFERENCES "public"."subjects"("id")
    ON DELETE CASCADE;

ALTER TABLE ONLY "public"."profiles"
    ADD CONSTRAINT "profiles_id_fkey"
    FOREIGN KEY ("id")
    REFERENCES "auth"."users"("id")
    ON DELETE CASCADE;

ALTER TABLE ONLY "public"."question_images"
    ADD CONSTRAINT "question_images_question_id_fkey"
    FOREIGN KEY ("question_id")
    REFERENCES "public"."questions"("id")
    ON DELETE CASCADE;


ALTER TABLE ONLY "public"."subjects"
    ADD CONSTRAINT "subjects_exam_board_id_fkey"
    FOREIGN KEY ("exam_board_id")
    REFERENCES "public"."exam_boards"("id")
    ON DELETE CASCADE;

ALTER TABLE ONLY "public"."tags"
    ADD CONSTRAINT "tag_parent_id_fkey"
    FOREIGN KEY ("parent_id")
    REFERENCES "public"."tags"("id")
    ON DELETE CASCADE;

ALTER TABLE ONLY "public"."user_questions"
    ADD CONSTRAINT "user_questions_question_id_fkey"
    FOREIGN KEY ("question_id")
    REFERENCES "public"."questions"("id")
    ON DELETE CASCADE;

ALTER TABLE ONLY "public"."user_questions"
    ADD CONSTRAINT "user_questions_user_id_fkey"
    FOREIGN KEY ("user_id")
    REFERENCES "auth"."users"("id")
    ON DELETE CASCADE;

ALTER TABLE ONLY "public"."question_chapters"
    ADD CONSTRAINT "question_chapters_question_id_fkey"
    FOREIGN KEY ("question_id")
    REFERENCES "public"."questions"("id")
    ON DELETE CASCADE;

ALTER TABLE ONLY "public"."question_chapters"
    ADD CONSTRAINT "question_chapters_chapter_id_fkey"
    FOREIGN KEY ("chapter_id")
    REFERENCES "public"."chapters"("id")
    ON DELETE CASCADE;
