
  create table "public"."user_questions" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "user_id" uuid not null,
    "question_id" bigint,
    "is_bookmarked" boolean not null default false,
    "completed_at" timestamp with time zone,
    "last_viewed_at" timestamp with time zone
      );


alter table "public"."user_questions" enable row level security;

alter table "public"."questions" drop column "complete";

CREATE UNIQUE INDEX user_questions_pkey ON public.user_questions USING btree (id);

CREATE UNIQUE INDEX user_questions_user_id_question_id_key ON public.user_questions USING btree (user_id, question_id);

alter table "public"."user_questions" add constraint "user_questions_pkey" PRIMARY KEY using index "user_questions_pkey";

alter table "public"."user_questions" add constraint "user_questions_question_id_fkey" FOREIGN KEY (question_id) REFERENCES public.questions(id) ON DELETE CASCADE not valid;

alter table "public"."user_questions" validate constraint "user_questions_question_id_fkey";

alter table "public"."user_questions" add constraint "user_questions_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;

alter table "public"."user_questions" validate constraint "user_questions_user_id_fkey";

alter table "public"."user_questions" add constraint "user_questions_user_id_question_id_key" UNIQUE using index "user_questions_user_id_question_id_key";

grant delete on table "public"."user_questions" to "anon";

grant insert on table "public"."user_questions" to "anon";

grant references on table "public"."user_questions" to "anon";

grant select on table "public"."user_questions" to "anon";

grant trigger on table "public"."user_questions" to "anon";

grant truncate on table "public"."user_questions" to "anon";

grant update on table "public"."user_questions" to "anon";

grant delete on table "public"."user_questions" to "authenticated";

grant insert on table "public"."user_questions" to "authenticated";

grant references on table "public"."user_questions" to "authenticated";

grant select on table "public"."user_questions" to "authenticated";

grant trigger on table "public"."user_questions" to "authenticated";

grant truncate on table "public"."user_questions" to "authenticated";

grant update on table "public"."user_questions" to "authenticated";

grant delete on table "public"."user_questions" to "postgres";

grant insert on table "public"."user_questions" to "postgres";

grant references on table "public"."user_questions" to "postgres";

grant select on table "public"."user_questions" to "postgres";

grant trigger on table "public"."user_questions" to "postgres";

grant truncate on table "public"."user_questions" to "postgres";

grant update on table "public"."user_questions" to "postgres";

grant delete on table "public"."user_questions" to "service_role";

grant insert on table "public"."user_questions" to "service_role";

grant references on table "public"."user_questions" to "service_role";

grant select on table "public"."user_questions" to "service_role";

grant trigger on table "public"."user_questions" to "service_role";

grant truncate on table "public"."user_questions" to "service_role";

grant update on table "public"."user_questions" to "service_role";


  create policy "user_questions.delete"
  on "public"."user_questions"
  as permissive
  for delete
  to public
using ((user_id = auth.uid()));



  create policy "user_questions.insert"
  on "public"."user_questions"
  as permissive
  for insert
  to public
with check ((user_id = auth.uid()));



  create policy "user_questions.select"
  on "public"."user_questions"
  as permissive
  for select
  to public
using ((user_id = auth.uid()));



  create policy "user_questions.update"
  on "public"."user_questions"
  as permissive
  for update
  to public
using ((user_id = auth.uid()))
with check ((user_id = auth.uid()));



